# "/" + ä»“åº“çš„åå­—. èµ„æºæ–‡ä»¶çš„è·¯å¾„ç»„æˆéƒ¨åˆ†
baseurl: "/my-first-blog"

# ç½‘é¡µçš„æ ‡é¢˜
title: "ç§‘æŠ€é‡è§å¥¹"
# ç½‘ç«™çš„ä¸»æ ‡é¢˜
name: "æˆ‘è¦å®Œæˆä¸€å°æ—¶ç¼–ç¨‹æŒ‘æˆ˜ ğŸ˜†"
# ç½‘ç«™å‰¯æ ‡é¢˜
description: "ğŸ¥³ è¿™æ˜¯æˆ‘çš„å°ä¸–ç•Œï¼Œç”¨äºè®°å½•ç”Ÿæ´»ï¼Œå·¥ä½œ"

# åˆ†é¡µé…ç½®
# æ¯é¡µæ–‡ç« æ•°é‡
paginate: 9

# å…¶å®ƒé…ç½®, å¯å¿½ç•¥, æ— éœ€ä¿®æ”¹
permalink: /:title/
paginate_path: /page:num/
plugins:
  - jekyll-paginate

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
lazyimages: "disabled"
exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
